var myName = "Jasline";
var myAge = 10;
var canVote = true;
var anything = "dog";
document.getElementById("tsStuff").innerHTML = "My name is" + myName;
document.write("canVote is a " + typeof (canVote) + "<br />");
document.write("myname is a" + typeof (myName) + "</br>");
document.write("anything is a " + typeof (anything) + "<br/>");
var strToNum = parseInt("5");
var numToStr = 5;
document.write("numToStr is a" + typeof (numToStr.toString()) + "<br/");
var PI = 3.14159;
